// Central types entrypoint — re-exports autogenerated Supabase types
// and exposes convenient aliases for use across the app.
import type { Database } from "./database.types";

export type {
	Database,
	Tables,
	TablesInsert,
	TablesUpdate,
	Enums,
	CompositeTypes,
	Json,
} from "./database.types";

export { Constants } from "./database.types";

// Convenience generics for table Row/Insert/Update access
export type TableRow<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Row"];

export type TableInsert<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Insert"];

export type TableUpdate<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Update"];

// Concrete aliases for commonly used tables
export type Admin = TableRow<"Admin">;
export type AdminInsert = TableInsert<"Admin">;
export type AdminUpdate = TableUpdate<"Admin">;

export type AdminLog = TableRow<"Admin_Log">;
export type AdminLogInsert = TableInsert<"Admin_Log">;
export type AdminLogUpdate = TableUpdate<"Admin_Log">;

export type Category = TableRow<"Category">;
export type CategoryInsert = TableInsert<"Category">;
export type CategoryUpdate = TableUpdate<"Category">;

export type Listing = TableRow<"Listing">;
export type ListingInsert = TableInsert<"Listing">;
export type ListingUpdate = TableUpdate<"Listing">;

export type Feedback = TableRow<"Feedback">;
export type FeedbackInsert = TableInsert<"Feedback">;
export type FeedbackUpdate = TableUpdate<"Feedback">;

// If you need UI-friendly shapes (e.g. nested `coordinate`), create
// mapped/transformed types here and use them in components.
export interface Coordinate {
	lat: number;
	lng: number;
}
