// Central types entrypoint — re-exports autogenerated Supabase types
// and exposes convenient aliases for use across the app.
import type { Database } from "./database.types";

export type {
	Database,
	Tables,
	TablesInsert,
	TablesUpdate,
	Enums,
	CompositeTypes,
	Json,
} from "./database.types";

export { Constants } from "./database.types";

// Convenience generics for table Row/Insert/Update access
export type TableRow<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Row"];

export type TableInsert<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Insert"];

export type TableUpdate<TableName extends keyof Database["public"]["Tables"]> =
	Database["public"]["Tables"][TableName]["Update"];

// Concrete aliases for commonly used tables
export type Admin = TableRow<"Admin">;
export type AdminInsert = TableInsert<"Admin">;
export type AdminUpdate = TableUpdate<"Admin">;

export type AdminLog = TableRow<"Admin_Log">;
export type AdminLogInsert = TableInsert<"Admin_Log">;
export type AdminLogUpdate = TableUpdate<"Admin_Log">;

export type Category = TableRow<"Category">;
export type CategoryInsert = TableInsert<"Category">;
export type CategoryUpdate = TableUpdate<"Category">;

export type Listing = TableRow<"Listing">;
export type ListingInsert = TableInsert<"Listing">;
export type ListingUpdate = TableUpdate<"Listing">;

export interface ListingWithCategory extends Listing {
  category: {
    category_name: string;
  };
}

export type Feedback = TableRow<"Feedback">;
export type FeedbackInsert = TableInsert<"Feedback">;
export type FeedbackUpdate = TableUpdate<"Feedback">;

// ─── UI-friendly shapes ───────────────────────────────────────────────────────
// These are narrow DTOs used by dropdowns and selects — they intentionally
// do not extend the full DB row so callers aren't forced to fetch unused columns.

/** Minimal category shape for use in dropdowns and selects. */
export interface CategoryOption {
	category_id: number;
	category_name: string;
}

/** Admin user shape shared between server actions and the AdminUserList UI. */
export interface AdminUser {
	admin_id: number;
	email: string;
	username: string;
}

export interface Coordinate {
	lat: number;
	lng: number;
}

